apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
  labels:
    app: monitoring
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v2.54.0
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
        - containerPort: 9090
      volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
    - name: grafana
      image: grafana/grafana:11.0.0
      ports:
        - containerPort: 3000
  volumes:
    - name: prometheus-config-volume
      configMap:
        name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eventsproject-service:8089']
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  selector:
    app: monitoring
  type: NodePort
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30090
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30030
