apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: bensalahons/events-project:2.0.O
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service.devops.svc.cluster.local:3306/eventsProjectDevOps?createDatabaseIfNotExist=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089
